// packages/create-volt/src/templates/svelte-ts/src/App.svelte
<script lang="ts">
  let count = $state(0);
</script>

<div class="app">
  <h1>Welcome to Volt!</h1>
  <p>Edit <code>src/App.svelte</code> and save to see changes.</p>
  <button onclick={() => count++}>
    Count: {count}
  </button>
</div>

<style>
  .app {
    max-width: 480px;
    margin: 0 auto;
    padding: 2rem;
    text-align: center;
  }
</style>

// packages/create-volt/src/templates/vue-ts/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div class="app">
    <h1>Welcome to Volt!</h1>
    <p>Edit <code>src/App.vue</code> and save to see changes.</p>
    <button @click="count++">
      Count: {{ count }}
    </button>
  </div>
</template>

<style scoped>
.app {
  max-width: 480px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}
</style>
